# Generated by Django 4.1.7 on 2024-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='DefaultID', max_length=50)),
                ('student_code', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('Pharmacy', 'Pharmacy'), ('EEE', 'Electrical and Electronic Engineering'), ('Textile', 'Textile Engineering'), ('Architecture', 'Architecture'), ('Bangla', 'Bangla Language and Literature'), ('English', 'English Language and Literature'), ('Economics', 'Economics'), ('LLB', 'Bachelor of Laws'), ('BBA', 'Bachelor of Business Administration')], default='CSE', max_length=100)),
                ('joining_year', models.IntegerField(default=2020)),
                ('leaving_year', models.IntegerField(blank=True, null=True)),
                ('batch', models.CharField(default='Batch01', max_length=10)),
                ('email', models.CharField(default='None', max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=100)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Tresarure', 'Tresarure'), ('General Secretary', 'General Secretary'), ('General Member', 'General Member'), ('Graphics Design', 'Graphics Design'), ('Research & Development', 'Research & Development')], default='Member', max_length=100)),
                ('facebook_link', models.CharField(default='None', max_length=100)),
                ('linkedin_link', models.CharField(default='None', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='members_photos/')),
            ],
        ),
    ]
