# Generated by Django 4.1.7 on 2024-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='batch',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='members',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='Blood Group', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='facebook_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='joining_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='linkedin_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
