# Generated by Django 4.1.7 on 2024-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_members_batch_alter_members_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
