# Generated by Django 4.1.7 on 2024-11-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
