# Generated by Django 4.1.7 on 2024-11-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certificate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_photos/'),
        ),
    ]
