# Generated by Django 4.1.7 on 2024-11-24 10:12

import app.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_certificate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('Pharmacy', 'Pharmacy'), ('EEE', 'EEE'), ('Textile', 'Textile'), ('Architecture', 'Architecture'), ('Bangla', 'Bangla'), ('English', 'English'), ('Economics', 'Economics'), ('LLB', 'LLB'), ('BBA', 'BBA')], max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('current_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('personal_email', models.EmailField(max_length=254)),
                ('personal_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='Blood Group', max_length=100)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('graphics_design', 'Graphics Design'), ('video_editing', 'Video Editing'), ('motion_graphics', 'Motion Graphics'), ('competitive_programming', 'Competitive Programming'), ('web_development', 'Web Development'), ('android_development', 'Android Development'), ('e_sports', 'E-Sports'), ('ui_ux_design', 'UI/UX Design'), ('event_management', 'Event Management'), ('content_writing', 'Content Writing'), ('photography', 'Photography'), ('paper_crafting', 'Paper Crafting'), ('volunteering', 'Volunteering'), ('singing', 'Singing'), ('dancing', 'Dancing'), ('anchoring', 'Anchoring'), ('debating', 'Debating'), ('other', 'Other')], max_length=241)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('graphics_design', 'Graphics Design'), ('video_editing', 'Video Editing'), ('motion_graphics', 'Motion Graphics'), ('competitive_programming', 'Competitive Programming'), ('web_development', 'Web Development'), ('android_development', 'Android Development'), ('e_sports', 'E-Sports'), ('ui_ux_design', 'UI/UX Design'), ('event_management', 'Event Management'), ('content_writing', 'Content Writing'), ('photography', 'Photography'), ('paper_crafting', 'Paper Crafting'), ('volunteering', 'Volunteering'), ('singing', 'Singing'), ('dancing', 'Dancing'), ('anchoring', 'Anchoring'), ('debating', 'Debating'), ('other', 'Other')], max_length=241)),
                ('experience_in_organization', models.BooleanField(default=False)),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('attached_to_other_clubs', models.BooleanField(default=False)),
                ('other_clubs_details', models.TextField(blank=True, null=True)),
                ('agree_meeting_attendance', models.BooleanField(default=False)),
                ('agree_program_participation', models.BooleanField(default=False)),
                ('agree_to_truthfulness', models.BooleanField(default=False)),
                ('agree_to_respectfulness', models.BooleanField(default=False)),
                ('agree_to_behavior', models.BooleanField(default=False)),
                ('agree_to_tools_usage', models.BooleanField(default=False)),
                ('agree_to_disciplinary_rules', models.BooleanField(default=False)),
                ('agree_to_general_member_terms', models.BooleanField(default=False)),
                ('joined_messenger_group', models.BooleanField(default=False)),
                ('facebook_profile_link', models.URLField(blank=True, max_length=300, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='apply_profile_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
    ]
