# Generated by Django 4.1.7 on 2024-11-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_clubjoinrequest_alter_certificate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('Pharmacy', 'Pharmacy'), ('EEE', 'EEE'), ('Textile', 'Textile'), ('Architecture', 'Architecture'), ('Bangla', 'Bangla'), ('English', 'English'), ('Economics', 'Economics'), ('LLB', 'LLB'), ('BBA', 'BBA')], default='CSE', max_length=20),
        ),
    ]
