# Generated by Django 4.1.7 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_clubjoinrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_meeting_attendance',
            field=models.BooleanField(default=False, help_text='I agree to attend all scheduled meetings unless excused.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_program_participation',
            field=models.BooleanField(default=False, help_text='I agree to actively participate in club programs and activities.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_behavior',
            field=models.BooleanField(default=False, help_text='I agree to maintain appropriate behavior in all club-related activities.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_disciplinary_rules',
            field=models.BooleanField(default=False, help_text="I agree to abide by the club's disciplinary rules and regulations."),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_general_member_terms',
            field=models.BooleanField(default=False, help_text='I agree to all general terms and conditions for membership.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_respectfulness',
            field=models.BooleanField(default=False, help_text='I agree to treat all members with respect.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_tools_usage',
            field=models.BooleanField(default=False, help_text='I agree to responsibly use club resources and tools.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='agree_to_truthfulness',
            field=models.BooleanField(default=False, help_text='I confirm that all information provided is truthful.'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='current_cgpa',
            field=models.DecimalField(decimal_places=2, default='', max_digits=4),
        ),
    ]
