# Generated by Django 4.1.7 on 2024-11-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_clubjoinrequest_agree_meeting_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubjoinrequest',
            name='attached_to_other_clubs',
        ),
        migrations.RemoveField(
            model_name='clubjoinrequest',
            name='experience_in_organization',
        ),
        migrations.RemoveField(
            model_name='clubjoinrequest',
            name='joined_messenger_group',
        ),
    ]
