# Generated by Django 4.1.7 on 2024-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_clubjoinrequest_agree_meeting_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='current_cgpa',
            field=models.FloatField(blank=True, default=2.5, null=True),
        ),
    ]
