# Generated by Django 4.1.7 on 2024-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_clubjoinrequest_current_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('Pharmacy', 'Pharmacy'), ('EEE', 'Electrical and Electronic Engineering'), ('Textile', 'Textile Engineering'), ('Architecture', 'Architecture'), ('Bangla', 'Bangla Language and Literature'), ('English', 'English Language and Literature'), ('Economics', 'Economics'), ('LLB', 'Bachelor of Laws'), ('BBA', 'Bachelor of Business Administration')], default='CSE', max_length=100)),
                ('batch', models.CharField(default='', max_length=10)),
                ('university_email', models.CharField(default='', max_length=100)),
                ('personal_email', models.CharField(default='', max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='Blood Group', max_length=100)),
                ('facebook_link', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='ClubJoinRequest/')),
                ('semester', models.CharField(default='', max_length=10)),
                ('current_cgpa', models.FloatField(blank=True, default=None, null=True)),
                ('personal_contact_number', models.CharField(default='', max_length=15)),
                ('emergency_contact_number', models.CharField(default='', max_length=15)),
                ('present_address', models.TextField(default='')),
                ('permanent_address', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='ClubJoinRequest',
        ),
    ]
