# Generated by Django 4.1.7 on 2024-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_applyclub_delete_clubjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyclub',
            name='semester',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
