# Generated by Django 4.1.7 on 2024-11-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_applyclub_experience_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyclub',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='applyclub',
            name='skills',
        ),
    ]
