# Generated by Django 4.1.7 on 2024-11-25 16:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_applyclub_interests_remove_applyclub_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyclub',
            name='agree_meeting_attendance',
            field=models.BooleanField(default=False, help_text='I will attend 80% of the club meetings'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_program_participation',
            field=models.BooleanField(default=False, help_text='I will not miss Two(2) consecutive programs.'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_behavior',
            field=models.BooleanField(default=False, help_text="I will be helpful and won't behave rudely to my junior studentsr"),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_disciplinary_rules',
            field=models.BooleanField(default=False, help_text='I will not leave SEUCC without the permission of the Executive Committee'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_general_member_terms',
            field=models.BooleanField(default=False, help_text='I will not be involved in any undisciplined activities. If I do so I will accept any punishment taken against me.'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_respectfulness',
            field=models.BooleanField(default=False, help_text='I will be respectful to my Faculties and senior students'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_tools_usage',
            field=models.BooleanField(default=False, help_text="I am able to use Viber and What's App on my mobile phone. I am using mobile data along with Wi-Fi on my phone."),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='agree_to_truthfulness',
            field=models.BooleanField(default=False, help_text='I will be truthful to Club Moderators and other members'),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='facebook_profile_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.profile_photo_upload_path),
        ),
    ]
