# Generated by Django 4.1.7 on 2024-11-25 16:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_applyclub_agree_meeting_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyclub',
            name='facebook_profile_link',
        ),
        migrations.RemoveField(
            model_name='applyclub',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='applyclub',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('graphics_design', 'Graphics Design'), ('video_editing', 'Video Editing'), ('motion_graphics', 'Motion Graphics'), ('competitive_programming', 'Competitive Programming'), ('web_development', 'Web Development'), ('android_development', 'Android Development'), ('e_sports', 'E-Sports'), ('ui_ux_design', 'UI/UX Design'), ('event_management', 'Event Management'), ('content_writing', 'Content Writing'), ('photography', 'Photography'), ('paper_crafting', 'Paper Crafting'), ('volunteering', 'Volunteering'), ('singing', 'Singing'), ('dancing', 'Dancing'), ('anchoring', 'Anchoring'), ('debating', 'Debating'), ('other', 'Other')], max_length=241),
        ),
        migrations.AddField(
            model_name='applyclub',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('graphics_design', 'Graphics Design'), ('video_editing', 'Video Editing'), ('motion_graphics', 'Motion Graphics'), ('competitive_programming', 'Competitive Programming'), ('web_development', 'Web Development'), ('android_development', 'Android Development'), ('e_sports', 'E-Sports'), ('ui_ux_design', 'UI/UX Design'), ('event_management', 'Event Management'), ('content_writing', 'Content Writing'), ('photography', 'Photography'), ('paper_crafting', 'Paper Crafting'), ('volunteering', 'Volunteering'), ('singing', 'Singing'), ('dancing', 'Dancing'), ('anchoring', 'Anchoring'), ('debating', 'Debating'), ('other', 'Other')], max_length=241),
        ),
        migrations.AlterField(
            model_name='applyclub',
            name='facebook_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
