# Generated by Django 4.1.7 on 2024-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_applyclub_interests_remove_applyclub_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyclub',
            name='portfolio_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
