# Generated by Django 4.1.7 on 2024-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_applyclub_portfolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyclub',
            name='portfolio_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
